### PR TITLE
Bug/dont require updating old events

### PR DESCRIPTION
**Pull request by mnelson4**
Work in progress. There are unit test failures indicating a problem currently.

## Problem this Pull Request solves

Fixes it so event managers don't need to manually update each event in order to trigger automated messages for it. See https://github.com/eventespresso/eea-automated-upcoming-event-notifications/issues/14
It does this by tweaking the SQL used to select for them (specifically, does a condition on a JOIN instead of inside the WHERE conditions)

## How has this been tested

* [ ] See Tony's testing note on https://github.com/eventespresso/eea-automated-upcoming-event-notifications/issues/14#issuecomment-550243004
* [ ] Test the global upcoming event and datetime notifications are sent for new events
* [ ] Test custom upcoming event and datetime notifications are sent for new events

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by mnelson4** [comment]
update: having an issue because globals are picking up registrations even when the event uses a custom template (because... it's hard to explain right now but it has to do with table joins.) ...

**Comment by mnelson4** [comment]
Ok I resolved the issue by using an event more tricky SQL query (it now involves a subquery) so it's just as well I didn't attempt modifying the models to support modifying the join statements (because that wouldn't have been enough).

@Pebblo are you comfortable reviewing? I think you're one of the team members most familiar with the functionality of AUEN right? Or if you prefer you could test instead.

**Comment by Pebblo** [comment]
Hey Mike,

I don't mind reviewing stuff but not sure I'll catch everything so it depends on what it is.

I went through this and nothing stood out to me so then I started testing and unfortunately, it looks like this doesn't solve the problem.

On a new site if I create 2 Events (Again AUEN 1 and AUEN 2) without the AUEN Add-on enabled, add an Approved registration to both events and then enable the AUEN Add-on and run its cron, it still doesn't pull in either of the registrations for those events until I update the event now that the add-on is enabled.

Not sure how much use this is to you but I'll throw it in here, I added a function to write the results of `getRegistrationsForMessageTemplateGroup()` to a file before it passed the results to `setKeysToRegistrationIds()` and also dumped out the last query. Theres some comments to show what I was doing (sorry i know its long):

```
// ===== Clean site, AUEN 1 + AUEN 2 created, NO AUEN Activated when updating events ==== //
[19-Nov-2019 20:10:34 UTC] Array
(
    [Query] => 
        SELECT 
          REG_ID AS REG_ID, 
          ATT_ID AS ATT_ID, 
          Registration.EVT_ID AS EVT_ID, 
          Registration.TXN_ID AS TXN_ID  
        FROM  
          wpta_esp_registration AS Registration 
          LEFT JOIN wpta_posts AS Event_CPT ON Event_CPT.ID=Registration.EVT_ID 
          LEFT JOIN wpta_esp_event_meta AS Event_Meta ON Event_CPT.ID = Event_Meta.EVT_ID  
          LEFT JOIN wpta_esp_datetime AS Event___Datetime ON Event___Datetime.EVT_ID=Event_CPT.ID 
          LEFT JOIN (
            SELECT emt.GRP_ID, emt.EVT_ID, mtp.MTP_deleted FROM 
            wpta_esp_event_message_template AS emt
            LEFT JOIN wpta_esp_message_template_group mtp ON emt.GRP_ID = mtp.GRP_ID AND mtp.MTP_message_type = 'automate_upcoming_event'
            ) AS emt_mtp ON Event_CPT.ID = emt_mtp.EVT_ID 
        WHERE 
          Registration.REG_deleted = 0  
          AND (Event_CPT.post_type = 'espresso_events')  
          AND ( (Event___Datetime.DTT_deleted = 0) OR Event___Datetime.DTT_ID IS NULL)  
          AND ( (emt_mtp.MTP_deleted = 0) OR emt_mtp.GRP_ID IS NULL) 
          AND Event_CPT.post_status IN ('publish','sold_out') 
          AND Event___Datetime.DTT_EVT_start BETWEEN '2019-11-19 20:10:34' AND '2019-11-24 23:40:34'
          AND Registration.STS_ID = 'RAP'
          AND (emt_mtp.GRP_ID=15
         OR emt_mtp.GRP_ID IS NULL) GROUP BY Registration.REG_ID
    [results] => Array
        (
        )

)

// Ran again to confirm nothing was selected.
[19-Nov-2019 20:18:17 UTC] Array
(
    [Query] => 
        SELECT 
          REG_ID AS REG_ID, 
          ATT_ID AS ATT_ID, 
          Registration.EVT_ID AS EVT_ID, 
          Registration.TXN_ID AS TXN_ID  
        FROM  
          wpta_esp_registration AS Registration 
          LEFT JOIN wpta_posts AS Event_CPT ON Event_CPT.ID=Registration.EVT_ID 
          LEFT JOIN wpta_esp_event_meta AS Event_Meta ON Event_CPT.ID = Event_Meta.EVT_ID  
          LEFT JOIN wpta_esp_datetime AS Event___Datetime ON Event___Datetime.EVT_ID=Event_CPT.ID 
          LEFT JOIN (
            SELECT emt.GRP_ID, emt.EVT_ID, mtp.MTP_deleted FROM 
            wpta_esp_event_message_template AS emt
            LEFT JOIN wpta_esp_message_template_group mtp ON emt.GRP_ID = mtp.GRP_ID AND mtp.MTP_message_type = 'automate_upcoming_event'
            ) AS emt_mtp ON Event_CPT.ID = emt_mtp.EVT_ID 
        WHERE 
          Registration.REG_deleted = 0  
          AND (Event_CPT.post_type = 'espresso_events')  
          AND ( (Event___Datetime.DTT_deleted = 0) OR Event___Datetime.DTT_ID IS NULL)  
          AND ( (emt_mtp.MTP_deleted = 0) OR emt_mtp.GRP_ID IS NULL) 
          AND Event_CPT.post_status IN ('publish','sold_out') 
          AND Event___Datetime.DTT_EVT_start BETWEEN '2019-11-19 20:18:17' AND '2019-11-24 23:48:17'
          AND Registration.STS_ID = 'RAP'
          AND (emt_mtp.GRP_ID=15
         OR emt_mtp.GRP_ID IS NULL) GROUP BY Registration.REG_ID
    [results] => Array
        (
        )

)

// ==== Updated AUEN 1 with the AUEN add-on activated, did NOT update AUEN 2 ==== //
// The registration assigned to AUEN 1 event is correctly pulled into this query.
[19-Nov-2019 20:18:51 UTC] Array
(
    [Query] => 
        SELECT 
          REG_ID AS REG_ID, 
          ATT_ID AS ATT_ID, 
          Registration.EVT_ID AS EVT_ID, 
          Registration.TXN_ID AS TXN_ID  
        FROM  
          wpta_esp_registration AS Registration 
          LEFT JOIN wpta_posts AS Event_CPT ON Event_CPT.ID=Registration.EVT_ID 
          LEFT JOIN wpta_esp_event_meta AS Event_Meta ON Event_CPT.ID = Event_Meta.EVT_ID  
          LEFT JOIN wpta_esp_datetime AS Event___Datetime ON Event___Datetime.EVT_ID=Event_CPT.ID 
          LEFT JOIN (
            SELECT emt.GRP_ID, emt.EVT_ID, mtp.MTP_deleted FROM 
            wpta_esp_event_message_template AS emt
            LEFT JOIN wpta_esp_message_template_group mtp ON emt.GRP_ID = mtp.GRP_ID AND mtp.MTP_message_type = 'automate_upcoming_event'
            ) AS emt_mtp ON Event_CPT.ID = emt_mtp.EVT_ID 
        WHERE 
          Registration.REG_deleted = 0  
          AND (Event_CPT.post_type = 'espresso_events')  
          AND ( (Event___Datetime.DTT_deleted = 0) OR Event___Datetime.DTT_ID IS NULL)  
          AND ( (emt_mtp.MTP_deleted = 0) OR emt_mtp.GRP_ID IS NULL) 
          AND Event_CPT.post_status IN ('publish','sold_out') 
          AND Event___Datetime.DTT_EVT_start BETWEEN '2019-11-19 20:18:51' AND '2019-11-24 23:48:51'
          AND Registration.STS_ID = 'RAP'
          AND (emt_mtp.GRP_ID=15
         OR emt_mtp.GRP_ID IS NULL) GROUP BY Registration.REG_ID
    [results] => Array
        (
            [0] => Array
                (
                    [REG_ID] => 1
                    [ATT_ID] => 15
                    [EVT_ID] => 13
                    [TXN_ID] => 1
                )

        )

)

// Re-ran the cron just to check it didn't pick anything else up after the above //
[19-Nov-2019 20:19:10 UTC] Array
(
    [Query] => 
        SELECT 
          REG_ID AS REG_ID, 
          ATT_ID AS ATT_ID, 
          Registration.EVT_ID AS EVT_ID, 
          Registration.TXN_ID AS TXN_ID  
        FROM  
          wpta_esp_registration AS Registration 
          LEFT JOIN wpta_posts AS Event_CPT ON Event_CPT.ID=Registration.EVT_ID 
          LEFT JOIN wpta_esp_event_meta AS Event_Meta ON Event_CPT.ID = Event_Meta.EVT_ID  
          LEFT JOIN wpta_esp_datetime AS Event___Datetime ON Event___Datetime.EVT_ID=Event_CPT.ID 
          LEFT JOIN (
            SELECT emt.GRP_ID, emt.EVT_ID, mtp.MTP_deleted FROM 
            wpta_esp_event_message_template AS emt
            LEFT JOIN wpta_esp_message_template_group mtp ON emt.GRP_ID = mtp.GRP_ID AND mtp.MTP_message_type = 'automate_upcoming_event'
            ) AS emt_mtp ON Event_CPT.ID = emt_mtp.EVT_ID 
        WHERE 
          Registration.REG_deleted = 0  
          AND (Event_CPT.post_type = 'espresso_events')  
          AND ( (Event___Datetime.DTT_deleted = 0) OR Event___Datetime.DTT_ID IS NULL)  
          AND ( (emt_mtp.MTP_deleted = 0) OR emt_mtp.GRP_ID IS NULL) 
          AND Event_CPT.post_status IN ('publish','sold_out') 
          AND Event___Datetime.DTT_EVT_start BETWEEN '2019-11-19 20:19:10' AND '2019-11-24 23:49:10'
          AND Registration.STS_ID = 'RAP'
          AND (emt_mtp.GRP_ID=15
         OR emt_mtp.GRP_ID IS NULL) AND Event_CPT.ID NOT IN (13) GROUP BY Registration.REG_ID
    [results] => Array
        (
        )

)

// ==== Updated AUEN 2 with the AUEN add-on activated ==== //
// Now the registration on AUEN 2 event is pulled into this query.
[19-Nov-2019 20:19:39 UTC] Array
(
    [Query] => 
        SELECT 
          REG_ID AS REG_ID, 
          ATT_ID AS ATT_ID, 
          Registration.EVT_ID AS EVT_ID, 
          Registration.TXN_ID AS TXN_ID  
        FROM  
          wpta_esp_registration AS Registration 
          LEFT JOIN wpta_posts AS Event_CPT ON Event_CPT.ID=Registration.EVT_ID 
          LEFT JOIN wpta_esp_event_meta AS Event_Meta ON Event_CPT.ID = Event_Meta.EVT_ID  
          LEFT JOIN wpta_esp_datetime AS Event___Datetime ON Event___Datetime.EVT_ID=Event_CPT.ID 
          LEFT JOIN (
            SELECT emt.GRP_ID, emt.EVT_ID, mtp.MTP_deleted FROM 
            wpta_esp_event_message_template AS emt
            LEFT JOIN wpta_esp_message_template_group mtp ON emt.GRP_ID = mtp.GRP_ID AND mtp.MTP_message_type = 'automate_upcoming_event'
            ) AS emt_mtp ON Event_CPT.ID = emt_mtp.EVT_ID 
        WHERE 
          Registration.REG_deleted = 0  
          AND (Event_CPT.post_type = 'espresso_events')  
          AND ( (Event___Datetime.DTT_deleted = 0) OR Event___Datetime.DTT_ID IS NULL)  
          AND ( (emt_mtp.MTP_deleted = 0) OR emt_mtp.GRP_ID IS NULL) 
          AND Event_CPT.post_status IN ('publish','sold_out') 
          AND Event___Datetime.DTT_EVT_start BETWEEN '2019-11-19 20:19:39' AND '2019-11-24 23:49:39'
          AND Registration.STS_ID = 'RAP'
          AND (emt_mtp.GRP_ID=15
         OR emt_mtp.GRP_ID IS NULL) AND Event_CPT.ID NOT IN (13) GROUP BY Registration.REG_ID
    [results] => Array
        (
            [0] => Array
                (
                    [REG_ID] => 2
                    [ATT_ID] => 16
                    [EVT_ID] => 14
                    [TXN_ID] => 2
                )

        )

)
```

So we still have the same issue where if you haven't updated the event it doesn't pull in registration for it. 

Please don't shoot the messenger :(

**Comment by mnelson4** [comment]
Nuts, but thanks @Pebblo. I'm double-checking...

**Comment by mnelson4** [comment]
Actually, unit tests are reproducing the issue. I probably got so excited that they were all fixed at one point, that when I tweaked the existing tests to reproduce issue #14 I overlooked that they were again failing...

**Comment by mnelson4** [comment]
:sparkles: inner join for the win! :sparkles: Fixed unit tests which were also reproducing the problem.

(Using an inner join instead of a left join means that other message types won't interfere because the subqueries won't include rows of the wrong message type, which were causing the main query to work with results rows that had other message type data instead of NO message data, which the query would then found failed the WHERE conditions... Ya it's tricky.)

Passing over to you again for a look Tony.

**Comment by Pebblo** [comment]
:sparkles: :star2: :fireworks:  **Winner winner chicken dinner!** :fireworks: :star2: :sparkles: 

Nice job Mike! Check this out:

```
[22-Nov-2019 10:41:42 UTC] Array
(
    [Query] => 
        SELECT 
          REG_ID AS REG_ID, 
          ATT_ID AS ATT_ID, 
          Registration.EVT_ID AS EVT_ID, 
          Registration.TXN_ID AS TXN_ID  
        FROM  
          wpta_esp_registration AS Registration 
          LEFT JOIN wpta_posts AS Event_CPT ON Event_CPT.ID=Registration.EVT_ID 
          LEFT JOIN wpta_esp_event_meta AS Event_Meta ON Event_CPT.ID = Event_Meta.EVT_ID  
          LEFT JOIN wpta_esp_datetime AS Event___Datetime ON Event___Datetime.EVT_ID=Event_CPT.ID 
          LEFT JOIN (
            SELECT emt.GRP_ID, emt.EVT_ID, mtp.MTP_deleted FROM 
            wpta_esp_event_message_template AS emt
            INNER JOIN wpta_esp_message_template_group mtp ON emt.GRP_ID = mtp.GRP_ID AND mtp.MTP_message_type = 'automate_upcoming_event'
            ) AS emt_mtp ON Event_CPT.ID = emt_mtp.EVT_ID 
        WHERE 
          Registration.REG_deleted = 0  
          AND (Event_CPT.post_type = 'espresso_events')  
          AND ( (Event___Datetime.DTT_deleted = 0) OR Event___Datetime.DTT_ID IS NULL)  
          AND ( (emt_mtp.MTP_deleted = 0) OR emt_mtp.GRP_ID IS NULL) 
          AND Event_CPT.post_status IN ('publish','sold_out') 
          AND Event___Datetime.DTT_EVT_start BETWEEN '2019-11-22 10:41:42' AND '2019-11-28 14:11:42'
          AND Registration.STS_ID = 'RAP'
          AND (emt_mtp.GRP_ID=17
        ) AND Event_CPT.ID NOT IN (16) GROUP BY Registration.REG_ID
    [results] => Array
        (
            [0] => Array
                (
                    [REG_ID] => 6
                    [ATT_ID] => 23
                    [EVT_ID] => 20
                    [TXN_ID] => 6
                )
        )
)

[22-Nov-2019 10:41:42 UTC] Array
(
    [Query] => 
        SELECT 
          REG_ID AS REG_ID, 
          ATT_ID AS ATT_ID, 
          Registration.EVT_ID AS EVT_ID, 
          Registration.TXN_ID AS TXN_ID  
        FROM  
          wpta_esp_registration AS Registration 
          LEFT JOIN wpta_posts AS Event_CPT ON Event_CPT.ID=Registration.EVT_ID 
          LEFT JOIN wpta_esp_event_meta AS Event_Meta ON Event_CPT.ID = Event_Meta.EVT_ID  
          LEFT JOIN wpta_esp_datetime AS Event___Datetime ON Event___Datetime.EVT_ID=Event_CPT.ID 
          LEFT JOIN (
            SELECT emt.GRP_ID, emt.EVT_ID, mtp.MTP_deleted FROM 
            wpta_esp_event_message_template AS emt
            INNER JOIN wpta_esp_message_template_group mtp ON emt.GRP_ID = mtp.GRP_ID AND mtp.MTP_message_type = 'automate_upcoming_event'
            ) AS emt_mtp ON Event_CPT.ID = emt_mtp.EVT_ID 
        WHERE 
          Registration.REG_deleted = 0  
          AND (Event_CPT.post_type = 'espresso_events')  
          AND ( (Event___Datetime.DTT_deleted = 0) OR Event___Datetime.DTT_ID IS NULL)  
          AND ( (emt_mtp.MTP_deleted = 0) OR emt_mtp.GRP_ID IS NULL) 
          AND Event_CPT.post_status IN ('publish','sold_out') 
          AND Event___Datetime.DTT_EVT_start BETWEEN '2019-11-22 10:41:42' AND '2019-11-27 14:11:42'
          AND Registration.STS_ID = 'RAP'
          AND (emt_mtp.GRP_ID=15
         OR emt_mtp.GRP_ID IS NULL) AND Event_CPT.ID NOT IN (11,12,15) GROUP BY Registration.REG_ID
    [results] => Array
        (
            [0] => Array
                (
                    [REG_ID] => 5
                    [ATT_ID] => 22
                    [EVT_ID] => 19
                    [TXN_ID] => 5
                )
            [1] => Array
                (
                    [REG_ID] => 7
                    [ATT_ID] => 24
                    [EVT_ID] => 21
                    [TXN_ID] => 7
                )
        )
)
```

Don't know what that is? Me neither!

Ok, ok, that's AUEN pulling in registrations linked to an event with NO AUEN template set (EVT_ID 21), an event WITH a global template AUEN set (EVT_ID 19) AND an event that is linked with a custom AUEN template (EVT_ID 20).

That all happens on a single cron.

----

I've been focused on the EVENT notifications so far and for those you get a :cookie: 

But now I'll take that one back because Datetime notifications are broken.... easy fix though.

**Comment by Pebblo** [comment]
A quick explanation to go with the above so you don't need to back track through the code.

In the first commit, `$data` is actually empty unless AUEN processed a non-global template prior to processing the global tamplate.

See: https://github.com/eventespresso/eea-automated-upcoming-event-notifications/blob/master/domain/services/commands/message/UpcomingNotificationsCommandHandler.php#L125

`$items_to_exclude` holds the ID's of datetimes that have the meta value set on them so I'm guessing this merge combines any datetimes ID's that may have happened on this specific request?

Either `$items_to_exclude` was empty on `getRegistrationsForDatetimeAndMessageTemplateGroupAndContext()` and needs at least `$items_to_exclude`

**Comment by mnelson4** [comment]
Oh oups and thanks! I'd like to add a unit test to avoid that regression...

**Comment by mnelson4** [comment]
Ok I added a test that shows your fix.
@joshfeck would you like a third person to review or test this? (Tony basically did both)

**Comment by Pebblo** [comment]
Spoke with Josh about this in Slack and he's fine with pushing this update live so merging in.

**Pull request merged**
